---
language: ruby
before_install:
  - "travis_retry gem install bundler || travis_retry gem install bundler -v 1.17.3"
  - "rm -f ${BUNDLE_GEMFILE}.lock"
before_script:
  - bundle update
cache: bundler
rvm:
- 2.2.10
- 2.3.8
- 2.4.5
- 2.5.3
- 2.6.8
- 2.7.4
- ruby-head
- rbx-2
- jruby
gemfile:
- gemfiles/rails_4.2.gemfile
- gemfiles/rails_5.0.gemfile
- gemfiles/rails_5.1.gemfile
- gemfiles/rails_5.2.gemfile
matrix:
  allow_failures:
  - rvm: rbx-2
  - rvm: jruby
  - rvm: ruby-head
  fast_finish: true
